---
- name: Pull
  docker_image:
    name: redis/redis-stack-server
    source: pull
- name: Enable Memory Overcommit (host)
  become: true
  lineinfile:
    dest: /etc/sysctl.conf
    line: "vm.overcommit_memory = 1"
- name: Enable Memory Overcommit (on-the-fly)
  become: true
  shell: sysctl -w vm.overcommit_memory=1
- name: Create network
  docker_network:
    name: redis
- name: Deploy
  docker_container:
    name: redis
    image: redis
    restart_policy: always
    command: redis-server --requirepass "{{ redis_password }}"
    volumes:
      - redis_data:/data
    networks:
      - name: redis
