---
- name: Add public key
  authorized_key:
    user: "{{ server_user_username }}"
    state: present
    key: "{{ sk_public_key }}"
- name: Configuration
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
- name: Restart
  systemd:
    name: sshd
    enabled: true
    state: restarted
