---
- name: Install
  become: true
  apt:
    name: ufw
    state: present
- name: Configuration
  become: true
  template:
    src: "{{ item }}.j2"
    dest: "/etc/ufw/{{ item }}"
  loop:
    - "user.rules"
    - "user6.rules"
- name: Start
  become: true
  ufw:
    state: enabled
