---
- name: Pull
  docker_image:
    name: portainer/portainer-ce
    source: pull
- name: Deploy
  docker_container:
    name: portainer
    image: portainer/portainer-ce
    restart_policy: always
    env:
      TZ: "Europe/London"
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
