---
- name: Pull
  docker_image:
    name: onlyoffice/documentserver
    source: pull
- name: Create network
  docker_network:
    name: onlyoffice
- name: Deploy
  docker_container:
    name: documentserver
    image: onlyoffice/documentserver
    restart_policy: always
    volumes:
      - onlyoffice_data:/var/www/onlyoffice/Data
      - onlyoffice_lib:/var/lib/olyoffice
      - onlyoffice_logs:/var/log/onlyoffice
    env:
      PUID: "1"
      GUID: "1"

      JWT_ENABLED: "true"
      JWT_SECRET: "{{ onlyoffice_jwt_secret }}"
      JWT_HEADER: AuthorizationJwt
      JWT_IN_BODY: "true"

      TZ: "Europe/London"
    labels:
      traefik.enable: "true"
      traefik.http.routers.onlyoffice.tls: "true"
      traefik.http.routers.onlyoffice.entrypoints: "websecure"
      traefik.http.routers.onlyoffice.rule: "Host(`office.{{ server_url }}`)"
      traefik.http.routers.onlyoffice.tls.certresolver: "letsencrypt"
      traefik.http.routers.onlyoffice.middlewares: "onlyoffice-headers"
      traefik.http.middlewares.onlyoffice-headers.headers.customresponseheaders.Access-Control-Allow-Origin: "*"
      traefik.http.middlewares.onlyoffice-headers.headers.customrequestheaders.X-Forwarded-Proto: "https"
      traefik.http.services.onlyoffice.loadbalancer.server.port: "80"
    networks:
      - name: traefik
      - name: onlyoffice
