---
- name: Install GPG
  become: true
  apt:
    name: gpg
    state: present
- name: Add GPG Key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: Add Repository
  become: true
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present
- name: Install
  become: true
  apt:
    name: ["docker-ce", "docker-ce-cli", "containerd.io", "docker-buildx-plugin", "docker-compose-plugin"]
    state: present
- name: Start
  become: true
  service:
    name: docker
    state: started
    enabled: yes
- name: Add to Docker group
  become: true
  user:
    name: "{{ server_user_username }}"
    groups: "docker"
    append: true
