---
- name: Provision a VPS
  hosts: all
  remote_user: "{{ server_user_username }}"

  vars:
  vars_files:
    - ../vault

  pre_tasks:
    - name: "apt : Upgrade all apt packages"
      become: true
      apt:
        update_cache: true
        force_apt_get: true
        autoremove: true
        autoclean: true
        cache_valid_time: 43200

  roles:
    - { name: firewall, tags: ["firewall"] }
    - { name: fail2ban, tags: ["fail2ban"] }
    - { name: docker, tags: ["docker"] }
    - { name: portainer, tags: ["portainer"] }
    - { name: traefik, tags: ["traefik"] }
    - { name: mariadb, tags: ["mariadb"] }
    - { name: redis, tags: ["redis"] }
    - { name: nextcloud, tags: ["nextcloud"] }
    - { name: onlyoffice, tags: ["onlyoffice"] }
    # - { name: wireguard, tags: ["wireguard"] } # Will finish at some point
